name: Decrypt and Push to Private Repository

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'The branch to push the decrypted file to'
        required: true
        default: 'main'

jobs:
  decrypt_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}

      - name: Import GPG private key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Create directory for decrypted files
        run: mkdir -p decrypted-files

      - name: Decrypt Files Recursively
        run: |
          shopt -s globstar
          for file in data/encrypted/**/*; do
            if [ -f "$file" ]; then
              # Skip the README.md file
              if [ "$(basename "$file")" = "README.md" ]; then
                echo "Skipping README.md file: $file"
                continue
              fi
              file_path="$(realpath "$file")"
              echo "Decrypting: \"$file_path\""
              # Remove the "data/encrypted/" prefix to get the relative path
              relative_path="${file#data/encrypted/}"
              echo "Relative path: \"$relative_path\""
              output_dir="decrypted-files/$(dirname "$relative_path")"
              mkdir -p "$output_dir"
              # Attempt to decrypt using the provided passphrase
              if gpg --quiet --batch --yes --pinentry-mode loopback --passphrase "$GPG_PASSPHRASE" \
                  --decrypt --output "$output_dir/$(basename "$file").json" "$file"; then
                echo "Decrypted successfully: \"$file_path\""
              else
                echo "Skipping non-GPG or failed decryption: \"$file_path\""
              fi
            fi
          done
        shell: bash
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Debug Decrypted Files
        run: ls -laR decrypted-files/

      - name: Set formatted date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Checkout Private Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPO_URL }}
          ref: main
          token: ${{ secrets.CONFIG_PRIVATE_REPO_TOKEN }}
          path: private-repo

      - name: Commit decrypted file to private repo
        run: |
          ls -la
          cp -r decrypted-files/* private-repo/data
          cd private-repo
          git add .
          git commit -m "Add decrypted file ${{ env.DATE }}"
          git push origin main
